### ISSUE TITLE
KiCad files

### ISSUE THREAD

**Issue by richard-scott** [ochin-space/ochin-CM4v2#1]
Please add the KiCad files to your repo so you can meet the requirements for the GPLv3.

**Comment by pernicious-flier** [comment]
Hi richard-scott, the license is for the documentation related to the ochin_CM4v2 board and not the board itself, the license is therefore respected. I am sorry but as I have explained in the past, it is precisely to defend the project that I decided not to provide the sources. For those who want to make a similar board or understand how it was made, he will find all the necessary information (including schematics) in the documentation.
Gerbers would be useless to any maker, as it is not possible to assemble such a board by hand guaranteeing its operation. 
Not to mention the costs that would be much higher than the price at which it is sold by Seeedstudio. 
These are the reasons, I think they are understandable and also in the interest of those who want this project to continue to exist.
Thank you for the question, I will add a note in the README.md of the project as soon as possible so as to clarify what the license is about.
Best, Flavio

**Comment by richard-scott** [comment]
If you didn't want to provide the source files then you should not have released this as GPL.

Under the terms of the GPL you need to provide the source files to allow anyone to generate any binary files distributed. May I refer you to this section that states you need to release the source code for any corresponding binary files.

https://github.com/ochin-space/ochin-CM4v2/blob/master/LICENSE#L337-L341

**Comment by pernicious-flier** [comment]
Ok , thank you for bringing it to my attention, I will read it as soon asap and consider whether I should use a more suitable license.
