### ISSUE TITLE
Wrong pinout on manual for USB EXT

### ISSUE THREAD

**Issue by Davidsastresas** [ochin-space/ochin-CM4v2#2]
Hi, we just purchased a few of these boards from seedstudio, and we were setting them up when we realized the USB EXT might be wrongly represented in the manual here:

https://github.com/ochin-space/ochin-CM4v2/blob/master/%C3%B6ch%C3%ACn%20CM4v2%20-%20Manual.pdf

We are pretty sure the pins are really the other way around as to how they are represented in the picture. So:

![Screenshot from 2024-08-04 14-45-20](https://github.com/user-attachments/assets/4f3620b4-2e9a-4d85-8549-e24c1f17cc36)

Would be instead, top to bottom, checking the pins as they are on that picture, with connectors on top and HDMI pointing down:

GND
VOTG
D+
D-
nRPiboot
+3V3
SCL1
SDA1

Is this correct? Can anybody confirm? Thanks!

**Comment by pernicious-flier** [comment]
> Hi, we just purchased a few of these boards from seedstudio, and we were setting them up when we realized the USB EXT might be wrongly represented in the manual here:
> 
> https://github.com/ochin-space/ochin-CM4v2/blob/master/%C3%B6ch%C3%ACn%20CM4v2%20-%20Manual.pdf
> 
> We are pretty sure the pins are really the other way around as to how they are represented in the picture. So:
> 
> ![Screenshot from 2024-08-04 14-45-20](https://github.com/user-attachments/assets/4f3620b4-2e9a-4d85-8549-e24c1f17cc36)
> 
> Would be instead, top to bottom, checking the pins as they are on that picture, with connectors on top and HDMI pointing down:
> 
> GND
> VOTG
> D+
> D-
> nRPiboot
> +3V3
> SCL1
> SDA1
> 
> Is this correct? Can anybody confirm? Thanks!

Hello David, thanks for the message i will check asap and let you know!
Best Flavio

**Comment by pernicious-flier** [comment]
Hello Davidsastresas, you were right... i've updated manual and pics.

Thanks a lot, Flavio
