### ISSUE TITLE
Ethernet setup not working

### ISSUE THREAD

**Issue by Davidsastresas** [ochin-space/ochin-CM4v2#3]
Hi, 

We purchased some of these boards from seedstudio. We verified several peripherals now, but we are having trouble with Ethernet port.

We soldered the jumpers as indicated in the manuals, and it seems the interface, drivers etc are on place, only it does not detect a valid connetion.

We also think it is correctly wired, and wires should be short enough ( similar wiring has been tested succesfully on other transformeless setups ), see photo attached:
![photo_5902183911620986879_y](https://github.com/user-attachments/assets/16d7cf25-8393-4564-b0d9-7af1a4ebc53b)

Before spending more time debugging it I wanted to check here first if anybody got this working already, or if I am missing something additional. Thanks!

**Comment by pernicious-flier** [comment]
Hello David, 
i confirm that the wiring seems to be fine, let me check on the latest board i received and i will let you know.
Best Flavio

**Comment by Davidsastresas** [comment]
Thank you very much Flavio.

Happy to read you confirm wiring to be fine. My first thought was wiring, so I got paranoid and checked continuity all the way up to cm4 pins.

I flashed a normal RPI OS image, and after not managing to make it work I also placed the custom ochin dt-blob.bin, although I don't think ethernet is managed there at all.

I also did a quick debug checking drivers and interfaces were up and running on my cm4, and it seems they were, everything pointed to a hardware or wiring issue.

I have 2 of these boards around, I will test the second one next time in case it is a faulty board. 

Let me know if you find any anditional info that could help me. But you helped a lot already confirming this to work, I was worried maybe the ethernet interface was not verified. Thank you very much!

**Comment by pernicious-flier** [comment]
Hello David,
i've tested the board connected through a TPlink AP and also p2p to an
ethernet camera and worked just fine. Let me test it again on the
seeedstudio latest board. I will let you know asap (hope in a couple of
days).
Best Flavio

Il giorno lun 19 ago 2024 alle ore 13:41 David Sastre <
***@***.***> ha scritto:

**Comment by pernicious-flier** [comment]
Hello David,
I have a question about your wirings, just to be sure: do the two devices
(ochin and the other ethernet device) share a common ground?
When one or both devices are transformerless the ground should be in common
to avoid the ground loop caused by the difference of potential of the two
grounds.
I don't see the ground connection in your photo, but the ground is the "-"
of the supply, if you power the two devices from the same source the ground
is already in common.
Please let me know,
Best, Flavio

Il giorno lun 19 ago 2024 alle ore 13:41 David Sastre <
***@***.***> ha scritto:

**Comment by Davidsastresas** [comment]
Thank you very much Flavio.

When I read your answer I got very happy because indeed I was powering the devices on 2 different power supplies and they didn't share ground, thanks for providing that info, I didn't realize!

However, I connected a common ground between the 2 of them ( gnd on ethernet port in ochin and ground directly on power supply of the other device ) and still not success.

Very frustrating, I am sure it is some dumb detail, but I am not managing to find the key. Please let me know if you think of anything else. I will report back if any news. Thank you!

**Comment by Davidsastresas** [comment]
I just got it working. I set up a second ochinv2 board, compute module, wiring, jumpers, etc from scratch and it is working now, even without common ground.

so most likely something was wrong on the first setup. Sorry for the trouble, and thank you very much for answering back. I am closing this one.

**Comment by pernicious-flier** [comment]
Thanks David to let us know, i appreciate it👍
Have fun with the ochins!

> I just got it working. I set up a second ochinv2 board, compute module, wiring, jumpers, etc from scratch and it is working now, even without common ground.
> 
> so most likely something was wrong on the first setup. Sorry for the trouble, and thank you very much for answering back. I am closing this one.
